//
//  main.swift
//  GenerateConstants
//
//  Created by Benjamin P Toews on 2/9/17.
//  Copyright © 2017 GitHub. All rights reserved.
//

import Foundation
import Security

func generateEnum(_ constants: [String: CFString]) {
    var enumString = ""

    // Find longest common prefix.
    let prefix = constants.keys.reduce(constants.keys.first!) { $1.commonPrefix(with: $0) }

    // Drop the first 'k' for the enum name.
    let name = prefix.substring(from: prefix.index(after: prefix.startIndex))

    print("enum \(name): String {", to: &enumString)

    for (const, value) in constants {
        // Case name is constant name without prefix.
        let caseName = const.substring(from: prefix.endIndex)

        print("  case \(caseName) = \"\(value)\" // \(const)", to: &enumString)
    }

    print("}", to: &enumString)

    print(enumString)
}

// Generated by `script/generate_constants`

generateEnum([
  "kSecAttrAccess": kSecAttrAccess,
  "kSecAttrAccessControl": kSecAttrAccessControl,
  "kSecAttrAccessGroup": kSecAttrAccessGroup,
  "kSecAttrAccessible": kSecAttrAccessible,
  "kSecAttrAccount": kSecAttrAccount,
  "kSecAttrApplicationLabel": kSecAttrApplicationLabel,
  "kSecAttrApplicationTag": kSecAttrApplicationTag,
  "kSecAttrAuthenticationType": kSecAttrAuthenticationType,
  "kSecAttrCanDecrypt": kSecAttrCanDecrypt,
  "kSecAttrCanDerive": kSecAttrCanDerive,
  "kSecAttrCanEncrypt": kSecAttrCanEncrypt,
  "kSecAttrCanSign": kSecAttrCanSign,
  "kSecAttrCanUnwrap": kSecAttrCanUnwrap,
  "kSecAttrCanVerify": kSecAttrCanVerify,
  "kSecAttrCanWrap": kSecAttrCanWrap,
  "kSecAttrCertificateEncoding": kSecAttrCertificateEncoding,
  "kSecAttrCertificateType": kSecAttrCertificateType,
  "kSecAttrComment": kSecAttrComment,
  "kSecAttrCreationDate": kSecAttrCreationDate,
  "kSecAttrCreator": kSecAttrCreator,
  "kSecAttrDescription": kSecAttrDescription,
  "kSecAttrEffectiveKeySize": kSecAttrEffectiveKeySize,
  "kSecAttrGeneric": kSecAttrGeneric,
  "kSecAttrIsInvisible": kSecAttrIsInvisible,
  "kSecAttrIsNegative": kSecAttrIsNegative,
  "kSecAttrIsPermanent": kSecAttrIsPermanent,
  "kSecAttrIssuer": kSecAttrIssuer,
  "kSecAttrKeyClass": kSecAttrKeyClass,
  "kSecAttrKeySizeInBits": kSecAttrKeySizeInBits,
  "kSecAttrKeyType": kSecAttrKeyType,
  "kSecAttrLabel": kSecAttrLabel,
  "kSecAttrModificationDate": kSecAttrModificationDate,
  "kSecAttrPRF": kSecAttrPRF,
  "kSecAttrPath": kSecAttrPath,
  "kSecAttrPort": kSecAttrPort,
  "kSecAttrProtocol": kSecAttrProtocol,
  "kSecAttrPublicKeyHash": kSecAttrPublicKeyHash,
  "kSecAttrRounds": kSecAttrRounds,
  "kSecAttrSalt": kSecAttrSalt,
  "kSecAttrSecurityDomain": kSecAttrSecurityDomain,
  "kSecAttrSerialNumber": kSecAttrSerialNumber,
  "kSecAttrServer": kSecAttrServer,
  "kSecAttrService": kSecAttrService,
  "kSecAttrSubject": kSecAttrSubject,
  "kSecAttrSubjectKeyID": kSecAttrSubjectKeyID,
  "kSecAttrType": kSecAttrType,
])

generateEnum([
  "kSecAttrKeyTypeRSA": kSecAttrKeyTypeRSA,
  "kSecAttrKeyTypeDSA": kSecAttrKeyTypeDSA,
  "kSecAttrKeyTypeAES": kSecAttrKeyTypeAES,
  "kSecAttrKeyTypeDES": kSecAttrKeyTypeDES,
  "kSecAttrKeyType3DES": kSecAttrKeyType3DES,
  "kSecAttrKeyTypeRC4": kSecAttrKeyTypeRC4,
  "kSecAttrKeyTypeRC2": kSecAttrKeyTypeRC2,
  "kSecAttrKeyTypeCAST": kSecAttrKeyTypeCAST,
  "kSecAttrKeyTypeECDSA": kSecAttrKeyTypeECDSA,
  "kSecAttrKeyTypeEC": kSecAttrKeyTypeEC,
  "kSecAttrKeyTypeECSECPrimeRandom": kSecAttrKeyTypeECSECPrimeRandom,
])

generateEnum([
  "kSecAttrCanEncrypt": kSecAttrCanEncrypt,
  "kSecAttrCanDecrypt": kSecAttrCanDecrypt,
  "kSecAttrCanDerive": kSecAttrCanDerive,
  "kSecAttrCanSign": kSecAttrCanSign,
  "kSecAttrCanVerify": kSecAttrCanVerify,
  "kSecAttrCanWrap": kSecAttrCanWrap,
  "kSecAttrCanUnwrap": kSecAttrCanUnwrap,
])

generateEnum([
  "kSecAttrKeyClassPublic": kSecAttrKeyClassPublic,
  "kSecAttrKeyClassPrivate": kSecAttrKeyClassPrivate,
  "kSecAttrKeyClassSymmetric": kSecAttrKeyClassSymmetric,
])

generateEnum([
  "kSecAttrAccessibleWhenUnlocked": kSecAttrAccessibleWhenUnlocked,
  "kSecAttrAccessibleAfterFirstUnlock": kSecAttrAccessibleAfterFirstUnlock,
  "kSecAttrAccessibleAlways": kSecAttrAccessibleAlways,
  "kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly": kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly,
  "kSecAttrAccessibleWhenUnlockedThisDeviceOnly": kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
  "kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly": kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,
  "kSecAttrAccessibleAlwaysThisDeviceOnly": kSecAttrAccessibleAlwaysThisDeviceOnly,
])

generateEnum([
  "kSecAttrIsInvisible": kSecAttrIsInvisible,
  "kSecAttrIsNegative": kSecAttrIsNegative,
  "kSecAttrIssuer": kSecAttrIssuer,
  "kSecAttrIsPermanent": kSecAttrIsPermanent,
  "kSecAttrIsSensitive": kSecAttrIsSensitive,
  "kSecAttrIsExtractable": kSecAttrIsExtractable,
])

generateEnum([
  "kSecReturnData": kSecReturnData,
  "kSecReturnAttributes": kSecReturnAttributes,
  "kSecReturnRef": kSecReturnRef,
  "kSecReturnPersistentRef": kSecReturnPersistentRef,
])
