//
//  Constants.swift
//  SwiftKeys
//
//  Created by Benjamin P Toews on 2/9/17.
//  Copyright © 2017 GitHub. All rights reserved.
//

import Foundation

/*
// This file is mostly auto-generated by `script/generate_constants`
*/

enum OtherKeys: String {
    case Class            = "class"        // kSecClass
    case MatchLimit       = "m_Limit"      // kSecMatchLimit
}

enum SecReturn: String {
    case Ref           = "r_Ref"           // kSecReturnRef
    case Data          = "r_Data"          // kSecReturnData
    case Attributes    = "r_Attributes"    // kSecReturnAttributes
    case PersistentRef = "r_PersistentRef" // kSecReturnPersistentRef
}

enum SecAttr: String {
    case Access              = "acls"   // kSecAttrAccess
    case AccessControl       = "accc"   // kSecAttrAccessControl
    case AccessGroup         = "agrp"   // kSecAttrAccessGroup
    case Accessible          = "pdmn"   // kSecAttrAccessible
    case Account             = "acct"   // kSecAttrAccount
    case ApplicationLabel    = "klbl"   // kSecAttrApplicationLabel
    case ApplicationTag      = "atag"   // kSecAttrApplicationTag
    case AuthenticationType  = "atyp"   // kSecAttrAuthenticationType
    case CanDecrypt          = "decr"   // kSecAttrCanDecrypt
    case CanDerive           = "drve"   // kSecAttrCanDerive
    case CanEncrypt          = "encr"   // kSecAttrCanEncrypt
    case CanSign             = "sign"   // kSecAttrCanSign
    case CanUnwrap           = "unwp"   // kSecAttrCanUnwrap
    case CanVerify           = "vrfy"   // kSecAttrCanVerify
    case CanWrap             = "wrap"   // kSecAttrCanWrap
    case CertificateEncoding = "cenc"   // kSecAttrCertificateEncoding
    case CertificateType     = "ctyp"   // kSecAttrCertificateType
    case Comment             = "icmt"   // kSecAttrComment
    case CreationDate        = "cdat"   // kSecAttrCreationDate
    case Creator             = "crtr"   // kSecAttrCreator
    case Description         = "desc"   // kSecAttrDescription
    case EffectiveKeySize    = "esiz"   // kSecAttrEffectiveKeySize
    case Generic             = "gena"   // kSecAttrGeneric
    case IsInvisible         = "invi"   // kSecAttrIsInvisible
    case IsNegative          = "nega"   // kSecAttrIsNegative
    case IsPermanent         = "perm"   // kSecAttrIsPermanent
    case Issuer              = "issr"   // kSecAttrIssuer
    case KeyClass            = "kcls"   // kSecAttrKeyClass
    case KeySizeInBits       = "bsiz"   // kSecAttrKeySizeInBits
    case KeyType             = "type"   // kSecAttrType/KeyType
    case Label               = "labl"   // kSecAttrLabel
    case ModificationDate    = "mdat"   // kSecAttrModificationDate
    case PRF                 = "prf"    // kSecAttrPRF
    case Path                = "path"   // kSecAttrPath
    case Port                = "port"   // kSecAttrPort
    case Proto               = "ptcl"   // kSecAttrProtocol
    case PublicKeyHash       = "pkhh"   // kSecAttrPublicKeyHash
    case Rounds              = "rounds" // kSecAttrRounds
    case Salt                = "salt"   // kSecAttrSalt
    case SecurityDomain      = "sdmn"   // kSecAttrSecurityDomain
    case SerialNumber        = "slnr"   // kSecAttrSerialNumber
    case Server              = "srvr"   // kSecAttrServer
    case Service             = "svce"   // kSecAttrService
    case Subject             = "subj"   // kSecAttrSubject
    case SubjectKeyID        = "skid"   // kSecAttrSubjectKeyID
}

public enum SecAttrKeyType: String {
    case RC2        = "23"         // kSecAttrKeyTypeRC2
    case RSA        = "42"         // kSecAttrKeyTypeRSA
    case TrippleDes = "17"         // kSecAttrKeyType3DES
    case DSA        = "43"         // kSecAttrKeyTypeDSA
    case DES        = "14"         // kSecAttrKeyTypeDES
    case AES        = "2147483649" // kSecAttrKeyTypeAES
    case RC4        = "25"         // kSecAttrKeyTypeRC4
    case EC         = "73"         // kSecAttrKeyTypeEC/ECDSA/ECSECPrimeRandom
    case CAST       = "56"         // kSecAttrKeyTypeCAST
}

public enum SecAttrCan: String {
    case Sign    = "sign" // kSecAttrCanSign
    case Unwrap  = "unwp" // kSecAttrCanUnwrap
    case Encrypt = "encr" // kSecAttrCanEncrypt
    case Wrap    = "wrap" // kSecAttrCanWrap
    case Verify  = "vrfy" // kSecAttrCanVerify
    case Derive  = "drve" // kSecAttrCanDerive
    case Decrypt = "decr" // kSecAttrCanDecrypt
}

public enum SecAttrKeyClass: String {
    case Public    = "0" // kSecAttrKeyClassPublic
    case Private   = "1" // kSecAttrKeyClassPrivate
    case Symmetric = "2" // kSecAttrKeyClassSymmetric
}

public enum SecAttrAccessible: String {
    case WhenUnlockedThisDeviceOnly     = "aku"  // kSecAttrAccessibleWhenUnlockedThisDeviceOnly
    case AlwaysThisDeviceOnly           = "dku"  // kSecAttrAccessibleAlwaysThisDeviceOnly
    case Always                         = "dk"   // kSecAttrAccessibleAlways
    case AfterFirstUnlockThisDeviceOnly = "cku"  // kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
    case WhenUnlocked                   = "ak"   // kSecAttrAccessibleWhenUnlocked
    case AfterFirstUnlock               = "ck"   // kSecAttrAccessibleAfterFirstUnlock
    case WhenPasscodeSetThisDeviceOnly  = "akpu" // kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly
}
